### ISSUE TITLE
Extension is not present on Packagist

### ISSUE THREAD

**Issue by gaumondp** [Apen/solradmin#1]
Even if there's a `composer.json`, there is no repository on Packagist.

` "name": "apen/solradmin",`

https://packagist.org/packages/apen/

**Comment by Apen** [comment]
True :-)

Must be good now.

**Comment by gaumondp** [comment]
Wow ! Merci!

We will test it and maybe over time provide some PR/MR if we got ideas. Like we did for Additionnal Scheduler.
